# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jasonwryan.com
title: jasonwryan.com
subtitle: Miscellaneous ephemeraâ€¦
author: Jason Ryan
simple_search: http://www.duckduckgo.com/
description: "Hacking. Writing. Hoping &rarr;"

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: / 
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 3          # Posts per page on the blog index
paginate_path: "blog/:num"  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: false      # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/pinboard.html, custom/asides/librefm.html, custom/asides/unixstack.html, custom/asides/arch.html]
page_asides: [asides/recent_posts.html, custom/asides/category_list.html, custom/asides/unixstack.html, custom/asides/arch.html]

# blog_index_asides:
# post_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Pinboard
pinboard_user: jasonwryan
pinboard_count: 3

# Libre.fm
librefm_user: jasonwryan
librefm_count: 5

# Disqus Comments
disqus_short_name: jasonwryan
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-907012-2

